services:
  db:
    image: postgres:17
    container_name: crypto_bot_db
    environment:
      POSTGRES_USER: crypto_bot_user
      POSTGRES_PASSWORD: crypto_bot_password
      POSTGRES_DB: crypto_bot
    ports:
      - 5432:5432
    volumes:
      - ./.pgdata:/var/lib/postgresql/data

volumes:
  .pgdata:
