services:
  db:
    image: postgres:17
    container_name: crypto_bot_db
    ports:
      - 5432:5432
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    networks:
      - app

  app:
    build: .
    container_name: crypto_bot_app
    volumes:
      - ./data:/app/data
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  data:
  .pgdata: